# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  version: '1.0.0.$(Build.BuildId)'  # ✅ Auto-increment with Build ID

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: Dotnet restore
  inputs:
    command: 'restore'
    projects: '**/*.csproj'


- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    
- powershell: |
    # Ensure the build output exists
    $packagePath = "$(Build.ArtifactStagingDirectory)\*.nupkg"
    $packageFile = Get-ChildItem -Path $packagePath | Select-Object -First 1
    
    if ($packageFile -eq $null) {
        Write-Host "No .nupkg file found in $(Build.ArtifactStagingDirectory)"
        exit 1  # Fail the pipeline if no package is found
    }

    # Extract package name and version
    $packageName = $packageFile.BaseName -replace '\.\d+\.\d+\.\d+.*$', ''
    $packageVersion = $packageFile.BaseName -replace '^.*\.(\d+\.\d+\.\d+.*)$', '$1'

    # Print extracted values
    Write-Host "Package File: $packageFile"
    Write-Host "Extracted Package Name: $packageName"
    Write-Host "Extracted Package Version: $packageVersion"

    # Set pipeline variables
    Write-Host "##vso[task.setvariable variable=artifactFullName]$packageName`_$packageVersion"
  displayName: 'Extract Artifact Name & Version from .nupkg'
  
    
- task: PublishSymbols@2
  displayName: Publish symbols path
  continueOnError: True
  inputs:
    SearchPattern: '**\bin\**\*.pdb'
    PublishSymbols: false
    SymbolServerType: TeamServices
    
- task: PublishBuildArtifacts@1
  displayName: Publish Artifact
  condition: succeededOrFailed()
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: $(artifactFullName)  # ✅ Includes version
    TargetPath: '\\my\share\$(Build.DefinitionName)\$(Build.BuildNumber)_$(artifactFullName)'  # ✅ Versioned target path
    

# ✅ Fix: Specify output directory for .nupkg files
- task: DotNetCoreCLI@2
  displayName: Dotnet Package
  inputs:
    command: 'pack'
    projects: '**/*.csproj'
    configuration: 'Release'
    arguments: '--output $(Build.ArtifactStagingDirectory) --property:Version=$(version)'

# ✅ Fix: Ensure .nupkg files exist before pushing
- task: NuGetCommand@2
  displayName: Push the nuget package to Feeds
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '8652216f-33ec-4cc4-912f-2fdda6d93168/ec7dd365-d6f2-4c11-a4e2-b5de5e9034c0'

