# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: my week13 livedemo for dotnet webapp auto ci pipeline

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest #self-hosted # ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        # Artifact name
        name: myminimalapi  # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: .
        # The desired behavior if no files are found using the provided path.

    - name: "Install Required Tools"
      run: |
          dotnet new tool-manifest
          dotnet tool install dotnet-reportgenerator-globaltool
          dotnet tool install dotnet-coverage
    - name: Run the unit tests with code coverage
      run: dotnet coverage collect dotnet test --filter TodoApiTests --output ${{ github.workspace }}/Tests/Coverage.cobertura.xml --output-format cobertura
    - name: Generate Report
      run: |
        dotnet reportgenerator -reports:${{ github.workspace }}/Tests/Coverage.cobertura.xml -targetdir:"${{ github.workspace }}/Tests/coveragereport" -reporttypes:"MarkdownSummary;Html" -assemblyfilters:+MinimalApi
    - name: Upload code coverage report
      uses: actions/upload-artifact@v4.6.0
      with:
        name: coveragereport
        path: ${{ github.workspace }}/Tests/coveragereport
        
    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: ${{ github.workspace }}/Tests/coveragereport/Summary.md

    - name: Configuring Tokens
      working-directory: ./Source
      run: |
        echo "USER1_TOKEN=$(dotnet user-jwts create --claim Username=user1 --claim Email=user1@example.com --name user1 --output token)" >> $GITHUB_ENV
        echo "USER2_TOKEN=$(dotnet user-jwts create --claim Username=user2 --claim Email=user2@example.com --name user2 --output token)" >> $GITHUB_ENV
    
    - name: Running Integration Tests
      run: dotnet test --filter TodoApiIntegrationTests
      
