name: my week13 livedemo for dotnet webapp auto ci pipeline

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # ✅ Install SonarScanner
    - name: Install SonarScanner
      run: dotnet tool install --global dotnet-sonarscanner

    # ✅ Begin SonarCloud analysis
    - name: SonarCloud Begin
      run: |
        dotnet sonarscanner begin \
          /k:"billchen247_MinimalApi" \
          /o:"billchen247" \
          /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
          /d:sonar.host.url="https://sonarcloud.io" \
          /d:sonar.cs.cobertura.reportsPaths="${{ github.workspace }}/Tests/Coverage.cobertura.xml"
          /d:sonar.projectBaseDir="${{ github.workspace }}"

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Install Required Tools
      run: |
        dotnet new tool-manifest
        dotnet tool install dotnet-reportgenerator-globaltool
        dotnet tool install dotnet-coverage

    - name: Run the unit tests with code coverage
      run: dotnet coverage collect dotnet test --filter TodoApiTests --output ${{ github.workspace }}/Tests/Coverage.cobertura.xml --output-format cobertura

    - name: Generate Report
      run: |
        dotnet reportgenerator \
          -reports:${{ github.workspace }}/Tests/Coverage.cobertura.xml \
          -targetdir:"${{ github.workspace }}/Tests/coveragereport" \
          -reporttypes:"MarkdownSummary;Html" \
          -assemblyfilters:+MinimalApi

    # ✅ End SonarCloud analysis
    - name: SonarCloud End
      run: dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

    - name: Upload code coverage report
      uses: actions/upload-artifact@v4.6.0
      with:
        name: coveragereport
        path: ${{ github.workspace }}/Tests/coveragereport

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: myminimalapi
        path: .
